Basic Redis functionality
microservices-course-itmo/saga pull request #10
Opened 2020-06-25 07:24 UTC by Vrx26

Реализация методов GET, SET и обработка переподключения.

2020-06-25 10:32 UTC, Anglopol requested changes

2020-06-25 10:32 UTC, Anglopol commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +    private static final int RECONNECT_INTERVAL=5; // Interval for reconnection to Redis Sentinel, when searching for new server.
Отформатируй, пожалуйста, код, это сделает его более читаемым и единообразным. Если ты работаешь в intellij IDEA можно использовать сочетание ctrl + alt + L

2020-06-25 10:32 UTC, Anglopol commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +    private io.lettuce.core.RedisClient redisClient; // Cached value for last used host
У тебя уже импортирована эта зависимость. Можно использовать просто RadisClient

2020-06-25 10:32 UTC, Anglopol commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +    private RedisClient GetMasterHost(){
Все методы нужно называть с маленькой буквы

2020-06-25 10:32 UTC, Anglopol commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +    private boolean handleConnectionBreak(int attempt) {
Мне кажется, что можно попробовать обойтись без использования рекурсии

2020-06-25 10:32 UTC, Anglopol commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +    private static final String CONNECTIONSTRING="redis-sentinel://localhost:23503,localhost:23504,localhost:23505/#mymaster";
Хардкодить подобные значение не стоит, лучше это вынести в application.properties

2020-06-25 10:59 UTC, shinehlina requested changes

2020-06-25 10:59 UTC, shinehlina commented on src/main/java/com/microservices/saga/choreography/supervisor/exception/RedisConnectionException.java
> +    public RedisConnectionException(String messagePattern, Throwable cause, Object... params) {
Можешь проверить, что этот конструктор точно можно вызвать? У меня есть сомнения, потому что может всегда вызываться только первый, так как "Object..." включает в себя "Throwable cause, Object... params"

2020-06-25 10:59 UTC, shinehlina commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +    private static final int RECONNECT_INTERVAL=5; // Interval for reconnection to Redis Sentinel, when searching for new server.
Лучше еще вместо комментариев javadoc написать

2020-06-25 10:59 UTC, shinehlina commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +    private static final String CONNECTIONSTRING="redis-sentinel://localhost:23503,localhost:23504,localhost:23505/#mymaster";
Может, есть что-то получше, чем "STRING" в названии переменной? Может, адрес или что-то типа того

2020-06-25 10:59 UTC, shinehlina commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +            connection.close();
Не получится ли так, что если мы вылетим отсюда с ошибкой, то соединение не будет закрыто?

2020-06-25 10:59 UTC, shinehlina commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +            connection.close();
Здесь тоже, можем его успеть открыть, но не закрыть

2020-06-25 10:59 UTC, shinehlina commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +                throw new RedisConnectionException("Cluster is unreachable",e);
Можешь сделать сообщения в исключениях немного осмысленнее?

2020-06-25 10:59 UTC, shinehlina commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +                throw new RedisConnectionException("Cluster is unreachable",e);
Можешь сделать сообщения в исключениях немного осмысленнее?

2020-06-25 10:59 UTC, shinehlina commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +                throw new RedisConnectionException("Interrupted",e);
Можешь сделать сообщения в исключениях немного осмысленнее? Вообще какой конструктор ты здесь вызываешь? Кажется, что вызовется `public RedisConnectionException(String messagePattern, Object... params) {`, но ты туда пытаешься cause пропихнуть...

2020-06-25 10:59 UTC, shinehlina commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +        return this.redisClient;
Это геттер, который ты используешь и как сеттер с логикой, и как конструктор. Наверное, стоит это как-то по-другому сделать. Геттер не должен менять состояния в идеале. Так что это надо как-то переписать...

И еще вопрос: а на "create" действительно происходит какое-то подключение или это просто инициализация?

2020-06-25 11:00 UTC, Anglopol requested changes

2020-06-25 11:00 UTC, Anglopol commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +        GetMasterHost();
Не очень понимаю смысл вынесения логики конструктора в отдельный метод

2020-06-25 11:12 UTC, Vrx26 commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +        return this.redisClient;
На create идет подключение к Sentinel нодам и они возвращают адрес текущего мастер нода, к которому потом все запросы идут.

2020-06-25 11:29 UTC, shinehlina commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +        return this.redisClient;
А эту штуку не нужно закрывать?

В любом случае вот этот метод странноват и нужно бы переписать)

2020-06-25 13:10 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/exception/RedisConnectionException.java
> +    public RedisConnectionException(String messagePattern, Throwable cause, Object... params) {
ну с виду да, но, думаю, компилятор умнее. А что идея пишет?

2020-06-25 13:10 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +    private static final int RECONNECT_INTERVAL=5; // Interval for reconnection to Redis Sentinel, when searching for new server.
мы все же выбрали подход с сантинелом?

2020-06-25 13:10 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +    private static final String CONNECTIONSTRING="redis-sentinel://localhost:23503,localhost:23504,localhost:23505/#mymaster";
в идеале мы должны находить реддисы через дискавери, но можно и через проперти

2020-06-25 13:10 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +            connection.close();
в finally или try-with-resources

2020-06-25 13:24 UTC, Vrx26 commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +    private static final int RECONNECT_INTERVAL=5; // Interval for reconnection to Redis Sentinel, when searching for new server.
Да, надежный кластер на 3 нодах нельзя поднять, я когда буду документацию писать распишу про это подробнее.

2020-06-25 13:27 UTC, Vrx26 commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +    private static final String CONNECTIONSTRING="redis-sentinel://localhost:23503,localhost:23504,localhost:23505/#mymaster";
Не совсем понял насчет дискавери. Эта строка с адресами нодов sentinel, мы к ним обращаемся и получаем ноды редиса

2020-06-27 18:29 UTC, Anglopol requested changes

2020-06-27 18:29 UTC, Anglopol commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +    private static final int RECONNECT_INTERVAL = 5; // Interval for reconnection to Redis Sentinel, when searching for new server.
javadoc вместо комментариев 
Должно быть так 
/**
* docs
**/
private static final ....
И так для каждого поля

2020-06-27 18:29 UTC, Anglopol commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +    private void setRedisClient(RedisClient client) {
private методы должны находиться ниже методов публичных

2020-06-27 18:29 UTC, Anglopol commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +                if (client.connect().sync().ping().equals("PONG")) {
"PONG" лучше вынести в отдельную static final переменную и дать ей осмысленное имя, иначе сначала может быть не понятно, что тут происходит

2020-06-27 18:29 UTC, Anglopol commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +    private boolean handleConnectionBreak() {
Не самое удачное название для функции, если функция имеет тип boolean, хорошим тоном считается называть ее так, чтобы ее имя начиналось с модального глагола. Когда видишь слово handle в названии, то кажется, что функция должна иметь тип void

2020-06-27 18:29 UTC, Anglopol commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +    private boolean handleConnectionBreak() {
Вообще не понимаю, зачем тут что-то возвращать, учитывая, что твоя функция либо возвращает true, либо кидает exception. Поэтому лучше сделай тип void (но название изменить стоит, так как у тебя здесь происходит реконнект, а не обработка обрыва подключения)

2020-06-27 18:29 UTC, Anglopol commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +            connection = this.redisClient.connect();
Использовать this. считается правильным только в конструкторах, здесь в этом нет смысла

2020-06-28 10:19 UTC, andrsuh requested changes

2020-06-28 10:19 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +        redisClient.shutdown();
npe?

2020-06-28 10:19 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +    public void shutdown() {
и где мы его будем вызывать?

2020-06-28 10:19 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +            value = get(key);
так это же бесконечно может происходить?

2020-06-28 10:19 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +    private RedisClient redisClient;
volatile а то ты ее так смело сетишь по 100 раз

2020-06-28 10:19 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +public class RedisClientWrapper {
ты сам это придумал? Если нет, кинь источник кода, потому что у меня он вызывает легкие сомнения

2020-06-28 10:19 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +            } catch (NullPointerException ignored) {
try-with-resourses не получится?

2020-06-28 10:23 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +    private static final String SentinelNodesAddresses = "redis-sentinel://localhost:23503,localhost:23504,localhost:23505/#mymaster";
это все в application.properties

2020-06-28 10:23 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +                RedisClient client = RedisClient.create(SentinelNodesAddresses);
а зачем новый клиент нужен?

2020-06-28 10:24 UTC, andrsuh commented
В данном пр должен быть добавлен еще раздел в композ, который поднимает редис. КРоме того, нужно пообщаться с Лешей и начать хранить в редисе инфу для метрик

2020-06-28 10:25 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +    private static final String CONNECTIONSTRING="redis-sentinel://localhost:23503,localhost:23504,localhost:23505/#mymaster";
ну через проперти

2020-06-28 10:26 UTC, andrsuh commented
Отвечай на каждый комментарий к пр, пожалуйста - либо ответ либо какой-то знак, что ты исправил замечание

2020-06-28 10:54 UTC, Vrx26 commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +    public void shutdown() {
В конце выполнения, перед кодом есть пример

2020-06-28 10:57 UTC, Vrx26 commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +public class RedisClientWrapper {
Не совсем понял начет этого

2020-06-28 10:57 UTC, Vrx26 commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +            } catch (NullPointerException ignored) {
Он лучше чем finally?

2020-06-28 10:58 UTC, Vrx26 commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +                RedisClient client = RedisClient.create(SentinelNodesAddresses);
Обращаемся к Sentinel нодам и получаем новый клиент

2020-06-28 10:59 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +            } catch (NullPointerException ignored) {
он читаемее и точно работает

2020-06-28 11:01 UTC, Vrx26 commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +        redisClient.shutdown();
Поправлю

2020-06-28 11:04 UTC, Vrx26 commented
> В данном пр должен быть добавлен еще раздел в композ, который поднимает редис. КРоме того, нужно пообщаться с Лешей и начать хранить в редисе инфу для метрик

А он не в отдельном репозитории должен быть?

2020-06-28 11:11 UTC, Vrx26 commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +            value = get(key);
Заменю на цикл

2020-06-28 11:13 UTC, Vrx26 commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +    private RedisClient redisClient;
Не совсем понял

2020-06-28 11:14 UTC, Vrx26 commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +    private static final String SentinelNodesAddresses = "redis-sentinel://localhost:23503,localhost:23504,localhost:23505/#mymaster";
Про это говорил в пятницу, что не получилось сделать. Иван сказал что посмотрит.

2020-06-28 11:29 UTC, Anglopol commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +    private static final String SentinelNodesAddresses = "redis-sentinel://localhost:23503,localhost:23504,localhost:23505/#mymaster";
Мы договорились что я посмотрю, когда ты запушишь свой нерабочий вариант получения данной строки из application.properties, чтоб понять, почему у тебя не получается

2020-06-28 13:10 UTC, andrsuh commented
да нет, в этом

2020-06-28 13:10 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +                RedisClient client = RedisClient.create(SentinelNodesAddresses);
почему старый вдруг стал плохим?

2020-06-28 13:11 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +    private static final String SentinelNodesAddresses = "redis-sentinel://localhost:23503,localhost:23504,localhost:23505/#mymaster";
аннотация @Value не помогает?

2020-06-28 13:12 UTC, Vrx26 commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +                RedisClient client = RedisClient.create(SentinelNodesAddresses);
Так ведь это метод для реконнекта - он вызывается если мы не можем по старому подключиться

2020-06-28 13:14 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +    private RedisClient redisClient;
нужно сделать переменную volatile. Ты сетишь ее много раз при выполнении кода, и это может происходить из нескольких потоков, что может привести к тому, что потоки имеют разное значение переменной

2020-06-28 13:15 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +            value = get(key);
это общепринятая практика? ретраить обращение к базе? ты сам этот паттерн придумал?

2020-06-28 13:20 UTC, Vrx26 commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +            value = get(key);
Тут нет особо других вариантов - или сразу выкидывать exception или попробовать подключиться к другому ноду

2020-06-30 18:02 UTC, Anglopol requested changes
Ты производил тестирование? Это работает?

2020-06-30 18:02 UTC, Anglopol commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +        for (int i=0; i<SERVER_CONNECTION_NUMBER;i++) {
Форматирование

2020-06-30 18:02 UTC, Anglopol commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +        for (int i=0; i<SERVER_CONNECTION_NUMBER;i++) {
Форматирование

2020-06-30 18:02 UTC, Anglopol commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +        String status;
Убрать объявление переменной в данном месте, как я понимаю, она вообще не нужна, можно просто делать return sync.set(..)

2020-06-30 18:02 UTC, Anglopol commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +                RedisCommands<String, String> sync = connection.sync();
Не самое понятное название для переменной

2020-06-30 18:02 UTC, Anglopol commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +            this.redisClient.shutdown();
Убрать this.

2020-06-30 18:02 UTC, Anglopol commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +                RedisCommands<String, String> sync = connection.sync();
Имя переменной

2020-06-30 18:02 UTC, Anglopol commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +            this.redisClient.shutdown();
Убрать this.

2020-06-30 18:10 UTC, Vrx26 commented
> Ты производил тестирование? Это работает?

У меня локально работает. Единственное, если запускать сервис не в докере то нужно свою строку для подключения прописать

2020-07-02 09:44 UTC, andrsuh requested changes

2020-07-02 09:44 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +            try (StatefulRedisConnection<String, String> connection = redisClient.connect()) {
коннекции нигде не кешируются? никакой пул не нужен?

2020-07-02 09:44 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +                String sentinelNodesAddresses = String.format("redis-sentinel://%s/#%s", sentinelNodesHosts, sentinelMasterName);
format очень дорогая операция, а ты очень часто вызываешь reconnect. Сохрани переменную в поле

2020-07-02 09:44 UTC, andrsuh commented on src/main/resources/application.properties
> +spring.redis.sentinel.nodes=redis-sentinel-1:26379,redis-sentinel-2:26379,redis-sentinel-3:26379
в файл для продакшена так же должны быть добавлены эти проперти

2020-07-02 09:45 UTC, Vrx26 commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +            try (StatefulRedisConnection<String, String> connection = redisClient.connect()) {
Вообще можно кэшировать, но тогда еще и его придется пользователю закрывать. Мне кажется нет в этом особого смысла

2020-07-02 09:47 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +                RedisClient client = RedisClient.create(SentinelNodesAddresses);
не знаю, ну как-то странно, клиент-то вряд ли от этого портится

2020-07-02 09:48 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +            try (StatefulRedisConnection<String, String> connection = redisClient.connect()) {
пулы коннекций не просто так придумали, странно что он под капотом сам не управляет

2020-07-02 09:56 UTC, Vrx26 commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +                RedisClient client = RedisClient.create(SentinelNodesAddresses);
Я не нашел метод который позволяет переподключиться без создания нового клиента, поэтому приходится так делать

2020-07-02 10:08 UTC, shinehlina commented
Вообще можно посмотреть на всякие клиенты, где реализованы как раз пулы и все такое. Посмотри, Jedis - это не то, что тебе надо? Узнай у Андрея

2020-07-03 14:46 UTC, andrsuh requested changes

2020-07-03 14:46 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +        } catch (NullPointerException ignored) {
перепиши. Программировать на исключениях это зло

2020-07-03 14:46 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +                    SentinelNodesAddresses = String.format("redis-sentinel://%s/#%s", sentinelNodesHosts, sentinelMasterName);
переменная с большой буквы

2020-07-03 14:46 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +                    SentinelNodesAddresses = String.format("redis-sentinel://%s/#%s", sentinelNodesHosts, sentinelMasterName);
ее нужно инициализировать как поле, не здесь

2020-07-03 14:46 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +    private GenericObjectPool<StatefulRedisConnection<String, String>> pool;
откуда ты вычитал такой подход? Разве у данной библиотеки нет своей поддержки пулов?

2020-07-03 14:46 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +    private GenericObjectPool<StatefulRedisConnection<String, String>> pool;
Давай будем использовать не первое решение в гугле, а сделанное на основе какого-то анализа

2020-07-03 14:56 UTC, Vrx26 commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +    private GenericObjectPool<StatefulRedisConnection<String, String>> pool;
Это решение напрямую из документации библиотеки 
https://github.com/lettuce-io/lettuce-core/wiki/Connection-Pooling

2020-07-03 14:57 UTC, Vrx26 commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +                    SentinelNodesAddresses = String.format("redis-sentinel://%s/#%s", sentinelNodesHosts, sentinelMasterName);
Я не могу инициализировать ее в контрукторе (Value инициализируется после него) поэтому здесь

2020-07-03 15:00 UTC, Vrx26 commented on src/main/java/com/microservices/saga/choreography/supervisor/redis/RedisClientWrapper.java
> +        } catch (NullPointerException ignored) {
Не совсем понял почему. Это ведь пересоздание ConnectionPool, как тут без исключения?

2020-07-05 12:20 UTC, andrsuh requested changes

2020-07-05 12:20 UTC, andrsuh commented on src/main/resources/application-docker-all.properties
> +spring.redis.sentinel.nodes=redis-sentinel-1:26379,redis-sentinel-2:26379,redis-sentinel-3:26379
тут все тоже через env

2020-10-21 11:14 UTC, closed without merging