project has logged
microservices-course-itmo/saga pull request #13
Opened 2020-06-28 14:03 UTC by borwi4ok

2020-06-28 14:22 UTC, shinehlina commented
Можешь себе в идее понаставить галочки типа optimize imports, cleanup и все такое. Либо пройтись по всем файлам с ctrl+alt+O и
 ctrl+alt+L

2020-06-29 18:41 UTC, shinehlina requested changes
Проверь везде пробелы, выбери что-то одно (или @Slf4j и использование log или получение через factory), отформатируй все и удали лишние импорты, проверь перегрузку toString у всего, что логируешь, проверить, что ты вообще даешь понять, о ком вообще речь идет: какой инстанс или чей дефинишн и тд). Добавь логи в контроллер

Я где-то написала, но не везде. Проверь, аналогичные места

2020-06-29 18:41 UTC, shinehlina commented on src/main/java/com/microservices/saga/choreography/supervisor/controller/DefinitionController.java
> +    private static final Logger logger = LoggerFactory.getLogger(
Ты же в этом файле ничего не логируешь. Хорошо бы логировать все запросы

2020-06-29 18:41 UTC, shinehlina commented on src/main/java/com/microservices/saga/choreography/supervisor/domain/entity/SagaStepDefinition.java
> +                "fail execution info{} timeout{}",
Пробелы надо бы понаставить

2020-06-29 18:41 UTC, shinehlina commented on src/main/java/com/microservices/saga/choreography/supervisor/domain/entity/SagaStepDefinition.java
> +                this.sagaName, this.stepName, this.successExecutionInfo,
У меня такое ощущение, что это не будет выглядеть красиво. Проверь, переопределен ли toString у всех сложных объектов. Если нет, то поставь, кому надо @ToString из ломбока

2020-06-29 18:41 UTC, shinehlina commented on src/main/java/com/microservices/saga/choreography/supervisor/kafka/KafkaClient.java
> +            logger.debug("Topics are subscribed:{}", newTopics);
Здесь тоже пробел

2020-06-29 18:41 UTC, shinehlina commented on src/main/java/com/microservices/saga/choreography/supervisor/kafka/KafkaClient.java
> +                    logger.debug("Event type is {}", eventBuilder.eventName(new String(header.value())));
Не очень поняла. Ты логируешь `event type`, но в логере - весь билдер (причем получается, что eventName сеттится 2 раза). Исправь, пожалуйста:)

2020-06-29 18:41 UTC, shinehlina commented on src/main/java/com/microservices/saga/choreography/supervisor/kafka/KafkaClient.java
> +        logger.debug("Success topics are {}, Fail topics are{}", successTopic, failTopic);
Я так понимаю, что тут хорошо бы указать, чьи это вообще топики (из step definition)

2020-06-29 18:41 UTC, shinehlina commented on src/main/java/com/microservices/saga/choreography/supervisor/kafka/KafkaClient.java
> +                    logger.error("Kafka Runtime exception", wakeupException);
Ты передаешь инстанс ошибки, но не вставляешь его в строку

2020-06-29 18:41 UTC, shinehlina commented on src/main/java/com/microservices/saga/choreography/supervisor/kafka/KafkaClient.java
> +                    logger.debug("Event type is {}", eventBuilder.eventName(new String(header.value())));
Вообще, наверное, надо бы где-то выше логировать. Здесь вообще непонятно, о чьих хедерах вообще идет речь

2020-06-29 18:41 UTC, shinehlina commented on src/main/java/com/microservices/saga/choreography/supervisor/service/DefinitionService.java
> +        logger.debug("Step definition{}", stepDefinition);
Здесь тоже пробел

2020-06-29 18:41 UTC, shinehlina commented on src/main/java/com/microservices/saga/choreography/supervisor/service/DefinitionService.java
> +        logger.info("Transition event is saved");
Какой?

2020-06-29 18:41 UTC, shinehlina commented on src/main/java/com/microservices/saga/choreography/supervisor/service/InstanceService.java
> +            logger.debug("Step name is equal to event name");
Не несет смысла. Как я поняла (может и неправильно) это просто значит, что мы уже захендлили этот ивент. Проверь, так ли это. Если так - надо бы и в логе написать, что за ивент вообще

2020-06-29 18:41 UTC, shinehlina commented on src/main/java/com/microservices/saga/choreography/supervisor/service/MeasureService.java
> +            logger.warn("No steps for saga with id {} found", sagaId);
Можешь подумать ли смысл логировать то, что написано в ошибке? Ты же ее все равно потом бросишь, где-то поймаешь и опять логировать будешь.

2020-06-29 18:41 UTC, shinehlina commented on src/main/java/com/microservices/saga/choreography/supervisor/service/ScheduleService.java
> +    private static final Logger logger = LoggerFactory.getLogger(
Опять же, здесь же ничего не логируется

2020-06-29 18:41 UTC, shinehlina commented on src/main/java/com/microservices/saga/choreography/supervisor/service/StatisticService.java
> +            logger.warn("Step list to analyze is empty");
здесь

2020-06-29 18:41 UTC, shinehlina commented on src/main/java/com/microservices/saga/choreography/supervisor/domain/entity/SagaStepDefinition.java
> +                "fail execution info{} timeout{}",
И подумай, не надо ли это выше логировать

2020-06-29 18:41 UTC, shinehlina commented on src/main/java/com/microservices/saga/choreography/supervisor/service/DefinitionService.java
> +        logger.debug("Step definition{}", stepDefinition);
И по идее надо написать, что ты регистрируешь новый степ

2020-06-29 18:41 UTC, shinehlina commented on src/main/java/com/microservices/saga/choreography/supervisor/service/DefinitionService.java
> +
Вот где-то в этом месте лучше написать, что ты его обновляешь

2020-06-29 18:41 UTC, shinehlina commented on src/main/java/com/microservices/saga/choreography/supervisor/service/InstanceService.java
>          if (sagaStepInstanceRepository.findSagaStepInstancesBySagaInstanceId(event.getSagaInstanceId()).stream()
Логируется ли где-то, что мы его захендлили?

2020-06-30 22:28 UTC, borwi4ok commented on src/main/java/com/microservices/saga/choreography/supervisor/domain/entity/SagaStepDefinition.java
> +                "fail execution info{} timeout{}",
Зачем логировать выше?

2020-07-01 11:31 UTC, Anglopol commented
Не стоит ресолвить конверсейшны. Ресолв должен ставить тот человек, который его открыл. Если ты исправил что-то, запушил код и конверсейшн не стал outdated автоматически, ты можешь просто написать в нем "исправлено". Но опять же, только после того, как код с изменениями будет запушен

2020-07-01 11:36 UTC, Anglopol commented on src/main/java/com/microservices/saga/choreography/supervisor/domain/entity/SagaStepDefinition.java
> +                "fail execution info{} timeout{}",
В том месте, где вызывается данный апдейт (выше по стеку).

2020-07-01 13:44 UTC, borwi4ok commented on src/main/java/com/microservices/saga/choreography/supervisor/domain/entity/SagaStepDefinition.java
> +                this.sagaName, this.stepName, this.successExecutionInfo,
`    public void update(SagaStepDefinition stepDefinition) {
        this.sagaName = stepDefinition.getSagaName();
        log.debug("Saga name is updated {}", this.sagaName);
        this.stepName = stepDefinition.getStepName();
        log.debug("Step name is updated {}", this.stepName);
        this.successExecutionInfo = stepDefinition.getSuccessExecutionInfo();
        log.debug("Success execution info {}", this.successExecutionInfo);
        this.failExecutionInfo = stepDefinition.getFailExecutionInfo();
        log.debug("Fail execution info {}", this.failExecutionInfo);
        this.timeout = stepDefinition.getTimeout();
        log.debug("Timeout started {}", this.timeout);
    }`

2020-07-01 13:45 UTC, borwi4ok commented on src/main/java/com/microservices/saga/choreography/supervisor/domain/entity/SagaStepDefinition.java
> +                this.sagaName, this.stepName, this.successExecutionInfo,
исправил

2020-07-01 13:45 UTC, borwi4ok commented on src/main/java/com/microservices/saga/choreography/supervisor/kafka/KafkaClient.java
> +            logger.debug("Topics are subscribed:{}", newTopics);
исправил

2020-07-01 13:46 UTC, borwi4ok commented on src/main/java/com/microservices/saga/choreography/supervisor/service/MeasureService.java
> +            logger.warn("No steps for saga with id {} found", sagaId);
понял,смысла нет,удалил этот лог

2020-07-01 13:46 UTC, borwi4ok commented on src/main/java/com/microservices/saga/choreography/supervisor/service/ScheduleService.java
> +    private static final Logger logger = LoggerFactory.getLogger(
исправил

2020-07-01 13:46 UTC, borwi4ok commented on src/main/java/com/microservices/saga/choreography/supervisor/service/StatisticService.java
> +            logger.warn("Step list to analyze is empty");
убрал

2020-07-03 01:06 UTC, borwi4ok commented on src/main/java/com/microservices/saga/choreography/supervisor/kafka/KafkaClient.java
> +                    logger.debug("Event type is {}", eventBuilder.eventName(new String(header.value())));
На счёт выше немного не понял,ведь здесь мы и сетим их,как я понял это первый вызов в этой цепочке методов.А по поводу билдера исправил

2020-07-03 14:51 UTC, andrsuh requested changes

2020-07-03 14:51 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/kafka/KafkaClient.java
> +        logger.info("Start listening");
очень информативно. Чем может помочь данный лог?

2020-07-03 14:51 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/kafka/KafkaClient.java
> +                    logger.info("Pooling messages");
это вообще все максимум debug

2020-07-03 14:51 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/service/DefinitionService.java
> +    private static final Logger logger = LoggerFactory.getLogger(
Почему мы не используем @Slf4?

2020-07-03 14:51 UTC, andrsuh commented on src/main/resources/logback.xml
> +            <maxHistory>30</maxHistory>
Думаю полдня-день вполне достаточно

2020-07-03 14:51 UTC, andrsuh commented on src/main/resources/logback.xml
> +            <totalSizeCap>10GB</totalSizeCap>
а где размер одного файла?

2020-07-03 14:54 UTC, borwi4ok commented on src/main/java/com/microservices/saga/choreography/supervisor/service/InstanceService.java
> +            logger.debug("Step name is equal to event name");
удалил

2020-07-03 15:06 UTC, borwi4ok commented on src/main/java/com/microservices/saga/choreography/supervisor/service/DefinitionService.java
> +
Добавил

2020-07-03 15:22 UTC, borwi4ok commented on src/main/java/com/microservices/saga/choreography/supervisor/service/InstanceService.java
>          if (sagaStepInstanceRepository.findSagaStepInstancesBySagaInstanceId(event.getSagaInstanceId()).stream()
Добавил

2020-07-03 15:23 UTC, borwi4ok commented on src/main/java/com/microservices/saga/choreography/supervisor/kafka/KafkaClient.java
> +                    logger.info("Pooling messages");
Я бы даже убрал эти логи,они мало о чём говорят

2020-07-03 15:23 UTC, borwi4ok commented on src/main/java/com/microservices/saga/choreography/supervisor/service/DefinitionService.java
> +    private static final Logger logger = LoggerFactory.getLogger(
уже исправил всё на @slf4j

2020-07-03 15:24 UTC, borwi4ok commented on src/main/resources/logback.xml
> +            <maxHistory>30</maxHistory>
сделаю день

2020-07-03 15:25 UTC, Anglopol commented
А ты можешь пушить сюда свои исправления?

2020-07-03 15:47 UTC, Anglopol requested changes

2020-07-03 15:47 UTC, Anglopol commented on src/main/java/com/microservices/saga/choreography/supervisor/controller/DefinitionController.java
> +import org.springframework.web.bind.annotation.*;
Так делать не надо, лучше вернуть как было

2020-07-03 15:47 UTC, Anglopol commented on src/main/java/com/microservices/saga/choreography/supervisor/domain/entity/SagaStepDefinition.java
> +import lombok.*;
Вернуть импорты как раньше

2020-07-03 15:49 UTC, Anglopol commented
Ты ресолвнул конфликт просто удалив весь код Алексея, это нужно исправить.

2020-07-04 15:52 UTC, andrsuh requested changes

2020-07-04 15:52 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/kafka/KafkaClient.java
> +                    log.error("Kafka Runtime exception");
Какую информацию можно вытянуть из данного сообщения?

2020-07-04 15:52 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/kafka/KafkaClient.java
> +                    log.debug("Event id is {}", eventBuilder.eventId(ByteBuffer.wrap(header.value()).getLong()));
вместо того, чтобы кешировать значение в переменную ты создал еще один буфер в памяти

2020-07-06 15:58 UTC, andrsuh requested changes

2020-07-06 15:58 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/service/DefinitionService.java
> +                updatedDefinition.getId(),
можно уже тогда просто updateDefinition передавать

2020-07-06 15:58 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/service/InstanceService.java
> +        log.debug("sagaStartTime = {}", sagaStartTime);
не очень полезно. Или зачем?

2020-07-06 15:58 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/service/InstanceService.java
> +        log.debug("sagaStartTime = {}", sagaStartTime);
тут как бы id инстанса нет, это не помогает

2020-07-06 15:58 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/service/InstanceService.java
> +//            logger.info(Events.I_CREATE_NEXT_INSTANCE_STEP,
и чего комменты?

2020-07-06 15:58 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/service/ScheduleService.java
> +                log.debug("Compensation has been sent for `{}` sagaID", sagaId);
Вот это как раз важная инфа, можно и посылать везде. По крайней мере, что компенсация как процесс началась

2020-07-06 15:58 UTC, andrsuh commented on src/main/resources/logback.xml
> +            <totalSizeCap>10GB</totalSizeCap>
?

2020-07-06 20:51 UTC, borwi4ok commented on src/main/java/com/microservices/saga/choreography/supervisor/service/DefinitionService.java
> +                updatedDefinition.getId(),
объект updatedDefinition?

2020-07-07 18:51 UTC, andrsuh commented
было бы неплохо как-то отвечать на комментарии)

2020-07-07 18:51 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/service/DefinitionService.java
> +                updatedDefinition.getId(),
да. toString сделать ему и передавать

2020-07-07 20:19 UTC, borwi4ok commented on src/main/java/com/microservices/saga/choreography/supervisor/service/InstanceService.java
> +        log.debug("sagaStartTime = {}", sagaStartTime);
мне кажется дебаг инфа лишней не будет,её не будет видно в kibana,это залогировал не через фасад,а 
через slf4j

2020-07-07 20:20 UTC, borwi4ok commented on src/main/java/com/microservices/saga/choreography/supervisor/service/InstanceService.java
> +//            logger.info(Events.I_CREATE_NEXT_INSTANCE_STEP,
с Лёшей завтра обсужу это,в этом классе как раз проблема с объявлением класса который взаимодействует с фасадом

2020-07-07 20:20 UTC, borwi4ok commented on src/main/java/com/microservices/saga/choreography/supervisor/service/ScheduleService.java
> +                log.debug("Compensation has been sent for `{}` sagaID", sagaId);
Закинул это в фасад и уровень теперь INFO

2020-07-25 12:03 UTC, andrsuh commented on .mvn/wrapper/MavenWrapperDownloader.java
> +public class MavenWrapperDownloader {
это вообще зачем?

2022-02-10 13:49 UTC, closed without merging