Prometheus and Grafana Integration
microservices-course-itmo/saga pull request #6
Opened 2020-06-22 12:34 UTC by alexstrive

2020-06-23 12:26 UTC, andrsuh reviewed
Все круто, но есть несколько коментов)

2020-06-23 12:26 UTC, andrsuh commented on prometheus.yml
> +    metrics_path: '/actuator/prometheus'
этот пусть актуален при отправке не через micrometer?

2020-06-23 12:26 UTC, andrsuh commented on prometheus.yml
> +      - targets: ['localhost:9090']
нужно оооочень подробные комменты ко всем пропертям. И здесь и в виде документации в notion.

2020-06-23 12:26 UTC, andrsuh commented on prometheus.yml
> +global:
этот файл конфигурирует сам прометей, нужно написать доку по поводу того, что этот файл не помещается в проект, а должен быть прокинут в контейнер с прометеем. Нужно создать отдельную репу для хранения и изменения этого файла, поскольку сервисов будет больше. Туда же можно поместить композ для прометея и графаны. Репу создавай в этом же спейсе

2020-06-23 12:26 UTC, andrsuh commented on prometheus.yml
> +global:
все должно быть отмечено в документации на отдельной страничку в notion

2020-06-23 12:26 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/SagaMetrics.java
> + * This Class expose methods for recording specific metrics
Очень хорошая и лаконичная дока! Спасибо

2020-06-23 12:26 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/SagaMetrics.java
> +    public static void incrementSagaTemplate(String sagaName) {
подумай, может быть, лучше `incrementSagaTemplate`

2020-06-23 12:26 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/SagaMetrics.java
> +public abstract class SagaMetrics {
нет никакой предпосылки делать класс абстрактным

2020-06-23 12:26 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/SagaMetrics.java
> +    public static void recordSagaInstanceStep(String sagaName, String stepName, double timeExecution) {
методы не делаем статическими. И используем DI для внедрения инстанса в нужные классы, пожалуйста

2020-06-23 12:26 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/components/PrometheusMetricsInjector.java
> +        var targetUrl = "/metrics-prometheus";
плиз доку подробнее

2020-06-23 12:26 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/components/PrometheusMetricsInjector.java
> +        var targetUrl = "/metrics-prometheus";
например, что за урл, что за метод, для чего

2020-06-23 12:26 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/components/SagaHelper.java
> +            SagaMetrics.incrementSagaTemplate(sagaTemplateName);
DI

2020-06-23 12:26 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/exception/FormattedRuntimeException.java
> +        SagaMetrics.incrementCoordinatorExceptionsThrown(this);
Ну нет, не все исключения стоит слать. Тем более, что они часто заворачиваются друг в друга и мы получим кучу инкрементов, когда хотим увидеть один главный

2020-06-23 12:26 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/kafka/KafkaClient.java
> +                        finally {
форматирование finally не надо с новой строки

2020-06-23 12:26 UTC, andrsuh commented on src/main/resources/application.properties
> +management.endpoints.web.exposure.include=*
может, не стоит все открывать?

2020-06-24 11:44 UTC, alexstrive commented on prometheus.yml
> +    metrics_path: '/actuator/prometheus'
Я предполагаю, что ты хотел написать "путь".

Нет, данный путь предназначен только для метрик, сгенерированными Micrometer.
Путь может быть только один у объявленного job. Так как там больше информации собирается: данные о JVM, CPU и так далее, то выбрал его.

2020-06-24 11:46 UTC, andrsuh commented on prometheus.yml
> +    metrics_path: '/actuator/prometheus'
ну я к этому и клюню, нужен коммент и дока

2020-06-24 11:48 UTC, alexstrive commented on src/main/java/com/microservices/saga/choreography/supervisor/SagaMetrics.java
> +    public static void incrementSagaTemplate(String sagaName) {
Метод ведь так и называется?

2020-06-24 11:54 UTC, alexstrive commented on prometheus.yml
> +global:
"Репу создавай в этом же спейсе" – в каком конкретно? В https://github.com/microservices-course-itmo или под своим именем? Если первое, то у меня нет прав, так как я не участник.

Я так понимаю, что я оставляю исключительно Prometheus и Grafana в docker-compose в этом репозитории?

2020-06-24 12:13 UTC, andrsuh commented on prometheus.yml
> +global:
второй вопрос не понял

2020-06-24 12:13 UTC, andrsuh commented on prometheus.yml
> +global:
права сейчас выдам

2020-06-24 12:17 UTC, alexstrive commented on prometheus.yml
> +global:
Сейчас в docker-compose 4 сервиса: Zookeeper, Kafka, Prometheus, Grafana. Мне стоит последние два (Prometheus, Grafana) вынести в отдельный docker-compose? Таким образом остается 2 в этом репозитории и 2 в новом.

2020-06-24 12:19 UTC, andrsuh commented on prometheus.yml
> +global:
https://github.com/microservices-course-itmo/metrics

2020-06-24 12:27 UTC, andrsuh commented on prometheus.yml
> +global:
да, все как ты написал

2020-06-24 13:48 UTC, alexstrive commented on prometheus.yml
> +global:
`remote: Permission to microservices-course-itmo/metrics.git denied to alexstrive.`

Не могу отправить комит в репозиторий. Могу через pull request оформить изменения.

2020-06-25 13:03 UTC, andrsuh requested changes

2020-06-25 13:03 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/components/SagaMetrics.java
> + * Prometheus' metrics exposed at /metrics-prometheus
`{@link PrometheusMetricsInjector#injectPrometheusServlet}`

2020-06-25 13:03 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/components/SagaMetrics.java
> +    public void incrementCoordinatorExceptionsThrown(Exception exception) {
может быть, count?

2020-06-25 13:03 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/exception/FormattedException.java
> +        sagaMetrics.incrementCoordinatorExceptionsThrown(this);
я уже объяснял почему считаю это неправильным

2020-06-25 13:03 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/exception/KafkaRuntimeException.java
> +        sagaMetrics.incrementCoordinatorExceptionsThrown(this);
про exceptions уже тоже писал

2020-06-25 13:03 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/exception/StepDefinitionNotFoundException.java
> +        sagaMetrics.incrementCoordinatorExceptionsThrown(this);
писал, это надо реализовывать другим способом

2020-06-25 13:03 UTC, andrsuh commented on src/main/resources/application.properties
> +management.endpoints.web.exposure.include=prometheus
проверил, что работает?

2020-06-25 13:04 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/SagaMetrics.java
> +    public static void incrementSagaTemplate(String sagaName) {
лучше count хочет написать, извиняюсь

2020-06-25 13:09 UTC, alexstrive commented on src/main/resources/application.properties
> +management.endpoints.web.exposure.include=prometheus
Да

2020-06-25 13:26 UTC, alexstrive commented on src/main/java/com/microservices/saga/choreography/supervisor/exception/FormattedException.java
> +        sagaMetrics.incrementCoordinatorExceptionsThrown(this);
Удалено

2020-06-25 13:26 UTC, alexstrive commented on src/main/java/com/microservices/saga/choreography/supervisor/exception/KafkaRuntimeException.java
> +        sagaMetrics.incrementCoordinatorExceptionsThrown(this);
Удалено

2020-06-25 13:26 UTC, alexstrive commented on src/main/java/com/microservices/saga/choreography/supervisor/exception/StepDefinitionNotFoundException.java
> +        sagaMetrics.incrementCoordinatorExceptionsThrown(this);
Удалено

2020-06-25 13:31 UTC, alexstrive commented on src/main/java/com/microservices/saga/choreography/supervisor/components/SagaMetrics.java
> + * Prometheus' metrics exposed at /metrics-prometheus
Добавлено. Метод дополнен документацией.

2020-06-25 13:34 UTC, alexstrive commented on src/main/java/com/microservices/saga/choreography/supervisor/components/SagaMetrics.java
> +    public void incrementCoordinatorExceptionsThrown(Exception exception) {
Изменено.

2020-06-26 20:07 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/components/SagaMetrics.java
> +    public void incrementCoordinatorExceptionsThrown(Exception exception) {
не вижу почему-то. Предлагаю сделать все методы с префиксом count

2020-06-28 10:00 UTC, andrsuh commented on src/main/java/com/microservices/saga/choreography/supervisor/components/SagaMetrics.java
> +    public void incrementCoordinatorExceptionsThrown(Exception exception) {
?

2020-06-28 10:02 UTC, andrsuh submitted a review, later dismissed
Прекрасно!

2020-06-28 13:09 UTC, Anglopol commented
Пока не надо мерджить, я напишу когда

2020-06-28 13:25 UTC, Anglopol submitted a review, later dismissed
Можно мерджить, но перед этим подмерджи к себе дев, мы перешли на мавен

2020-06-28 15:59 UTC, alexstrive commented
Обновлено

2020-07-01 13:52 UTC, andrsuh submitted a review, later dismissed

2020-07-01 14:37 UTC, andrsuh approved these changes

2020-07-01 14:46 UTC, merged